# Grammar for subset of JSON
# String doesn't support unicode and escape yet
# If you don't need to generate unicode and escape, you can use this grammar
# We are working to support unicode and escape

root ::= object

object ::= "{" ws fields "}" ws

fields ::= '"name"' ws ":" ws string "," ws '"avg_price"' ws ":" ws number "," ws '"unit"' ws ":" ws unit ws

value ::= object | array | string | number | ("true" | "false" | "null") ws

array ::= "[" ws ( value ("," ws value)* )? "]" ws

string ::= "\"" [ \t!#-\[\]-~]* "\"" ws

number ::= ("-"? ([0-9] | [1-9] [0-9]*)) ("." [0-9]+)? ([eE] [-+]? [0-9]+)? ws

unit ::= "\"" [ \t!#-\[\]-~]* "\"" ws

ws ::= ([ \t\n] ws)?
